# -*- coding: utf-8 -*-
"""clean_file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qE1UjAKo6n2ZhY8X491aY3C9oYa_Srkb
"""

"""
VER 2 
Removes unwanted lines of data from file 
Inputs:
  - textFile: file of choice to clean up
  - break_msg: strings of messages to use to find unwanted lines of data
  - saveName: name assigned to file to be saved as
  - saveDir: directory to save cleaned up files to
"""
def cleanFile(textFile, break_msg, saveName, saveDir):
  range1 = [i for i in range(0,7)]
  fileRead = pd.read_table(textFile, usecols = range1, sep='\t',\
                            delim_whitespace=True, dtype = {"TIMESTAMP":int, \
                            "RIGHT_EYE_X":object, "RIGHT_EYE_Y":object, \
                            "RIGHT_PUPIL_SIZE":object, "LEFT_EYE_X":object, \
                            "LEFT_EYE_Y":object, "LEFT_EYE_PUPIL":object}, \
                            low_memory=False)
  fileRead.columns = ["TIMESTAMP", "RIGHT_EYE_X", "RIGHT_EYE_Y", \
                      "RIGHT_PUPIL_SIZE", "LEFT_EYE_X", "LEFT_EYE_Y",\
                      "LEFT_EYE_PUPIL"]
  rowCount = fileRead.shape[0]
  listDrop = list()
  newFile = fileRead
  newFile = pd.DataFrame(newFile, columns = ["TIMESTAMP", "RIGHT_EYE_X", \
                                             "RIGHT_EYE_Y", "RIGHT_PUPIL_SIZE",\
                                             "LEFT_EYE_X", "LEFT_EYE_Y", \
                                             "LEFT_EYE_PUPIL"])
  colCount = 7
  msgCount = np.zeros(rowCount, dtype = int)
  currRow = 0
  while currRow < rowCount:
    startRow = 1
    endRow = 1
    s_drop = str(fileRead.iloc[currRow, 0])
    res_drop = s_drop.translate(str.maketrans('','','1234567890'))
    if res_drop != '':
      listDrop = listDrop.append(currRow)
      currRow = currRow + 1
    else:
      currRow = currRow + 1
  newFile = newFile.drop(listDrop)
  np.savetxt(saveDir+''+str(saveName), newFile, delimiter=" ", fmt="%s")