# -*- coding: utf-8 -*-
"""count_trial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qE1UjAKo6n2ZhY8X491aY3C9oYa_Srkb
"""

"""
Seperates raw .asc or .txt file by trials, and saves each trial into directory of choice
Inputs: 
  - textFile: full path to a .asc or .txt file
  - saveDir: directory to save files to
  - patientNum: patient number
Outputs: 
  - trialIndex: a list of all the trial numbers and their start and end time stamps
"""
def countTrials(textFile, saveDir, patientNum):
  range1 = [i for i in range(0,7)]
  fileRead = pd.read_table(textFile, usecols = range1, sep='\t',\
                            delim_whitespace=True, dtype = {"TIMESTAMP":int, \
                            "RIGHT_EYE_X":object, "RIGHT_EYE_Y":object, \
                            "RIGHT_PUPIL_SIZE":object, "LEFT_EYE_X":object, \
                            "LEFT_EYE_Y":object, "LEFT_EYE_PUPIL":object}, \
                            low_memory=False)
  fileRead.columns = ["TIMESTAMP", "RIGHT_EYE_X", "RIGHT_EYE_Y", \
                      "RIGHT_PUPIL_SIZE", "LEFT_EYE_X", "LEFT_EYE_Y",\
                      "LEFT_EYE_PUPIL"]
  #print(fileRead.iloc[150:170,0])
  rowCount = fileRead.shape[0]
  colCount = 7
  sample = "SAMPLE"
  end = "END"
  currRow = 1
  trialNum = 1
  trialIndex = [[0,0,0]];
  trialIndex = pd.DataFrame(trialIndex)
  newFile = [[0,0,0,0,0,0,0]]
  newFile = pd.DataFrame(newFile, columns = ["TIMESTAMP", "RIGHT_EYE_X", "RIGHT_EYE_Y", \
                      "RIGHT_PUPIL_SIZE", "LEFT_EYE_X", "LEFT_EYE_Y",\
                      "LEFT_EYE_PUPIL"])
  while currRow < rowCount:
    startRow = 1
    endRow = 1
    if sample in str(fileRead.iloc[currRow, 0]):
      #print("yes"+str(currRow))
      startRow = currRow
      currRowTemp = currRow
      while currRowTemp < rowCount:
        if end in str(fileRead.iloc[currRowTemp, 0]):
          #print("end found"+str(currRowTemp))
          endRow = currRowTemp
          currRow = currRowTemp
          break
        else:
          currRowTemp = currRowTemp + 1
      trialIndex = trialIndex.append([[str(trialNum), str(startRow), \
                                       str(endRow)]], ignore_index=True)
      newFile = newFile.append(fileRead.iloc[startRow:endRow,:], \
                               ignore_index=True)
      trialNum = trialNum + 1
    else:
      currRow = currRow + 1
  trialNum = trialNum - 1
  trialIndex.columns = ["TRIAL NUM", "TRIAL START", "TRIAL END"]
  np.savetxt(saveDir+"NLS_"+str(patientNum)+"_Clean.txt.gz", newFile, \
             delimiter=" ", fmt="%s")
  return trialIndex