# -*- coding: utf-8 -*-
"""read_messages

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qE1UjAKo6n2ZhY8X491aY3C9oYa_Srkb
"""

"""
Searches through each file to save different message types and their time stamps
Inputs: 
  - textFile: textFile to be searched through
  - msgStatements: previously found msgStatements
  - msgTimes: previously marked time stamps
Outputs:
  - msgStatements: updated found msgStatements
  - msgTimes: updated marked time
"""
def readMessages(textFile, patientNum, saveDir):
  msgStatements=[]
  msgTimes=[]
  range1 = [i for i in range(0,7)]
  fileRead = pd.read_table(textFile, usecols = range1, sep='\t',\
                            delim_whitespace=True, dtype = {"TIMESTAMP":int, \
                            "RIGHT_EYE_X":object, "RIGHT_EYE_Y":object, \
                            "RIGHT_PUPIL_SIZE":object, "LEFT_EYE_X":object, \
                            "LEFT_EYE_Y":object, "LEFT_EYE_PUPIL":object}, \
                            low_memory=False)
  fileRead.columns = ["TIMESTAMP", "RIGHT_EYE_X", "RIGHT_EYE_Y", \
                      "RIGHT_PUPIL_SIZE", "LEFT_EYE_X", "LEFT_EYE_Y",\
                      "LEFT_EYE_PUPIL"]
  rowCount = fileRead.shape[0]
  msg = "MSG"
  currRow = 0
  while currRow < rowCount:
    startRow = 1
    endRow = 1
    if msg in str(fileRead.iloc[currRow, 0]) :
      s = str(fileRead.iloc[currRow, 2])
      res = s.translate(str.maketrans('','','1234567890'))
      res = res.translate(str.maketrans('', '', '-'))
      s_time = str(fileRead.iloc[currRow, 1])
      #abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ
      res_time = s_time.translate(str.maketrans('','',''))
      if res != '':
        #print(res)
        #print(res_time)
        msgStatements.append(res)
        msgTimes.append(res_time)
      currRow = currRow + 1
    else:
      currRow = currRow + 1
  np.savetxt(saveDir+"NLS_"+str(patientNum)+"_Statements.txt.gz", \
             msgStatements, delimiter=" ", fmt="%s")
  np.savetxt(saveDir+"NLS_"+str(patientNum)+"_Times.txt.gz", \
             msgTimes, delimiter=" ", fmt="%s")
  return msgStatements, msgTimes