# -*- coding: utf-8 -*-
"""saccCount

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qE1UjAKo6n2ZhY8X491aY3C9oYa_Srkb
"""

"""
Counts and stores the number of saccade occurances
Inputs: 
  - textFile: file of text to be combed through for saccade occurances
  - ssaccCount: previous number of saccades counted
Output:
  - ssaccCount: updated number of saccades found
"""
def saccCount(textFile, ssaccCount):
  range1 = [i for i in range(0,7)]
  fileRead = pd.read_table(textFile, usecols = range1, sep='\t',\
                            delim_whitespace=True, dtype = {"TIMESTAMP":int, \
                            "RIGHT_EYE_X":object, "RIGHT_EYE_Y":object, \
                            "RIGHT_PUPIL_SIZE":object, "LEFT_EYE_X":object, \
                            "LEFT_EYE_Y":object, "LEFT_EYE_PUPIL":object}, \
                            low_memory=False)
  rowCount = fileRead.shape[0]
  currRow = 0
  while currRow < rowCount:
    startRow = 1
    endRow = 1
    if "SSACC" in str(fileRead.iloc[currRow, 0]):
      s = str(fileRead.iloc[currRow, 2])
      ssaccCount.append(s)
      currRow = currRow + 1
    else:
      currRow = currRow + 1
  return ssaccCount